### ISSUE TITLE
Hide Auto Shot Castbar

### ISSUE THREAD

**Issue by RonanGH** [SabineWren/Quiver#1]
Would it be possible to add an option to hide the Auto Shot Castbar when you're not using Auto Shot (or when you're out of combat)?

**Comment by SabineWren** [comment]
Type `/qq` or `/quiver`. There's an "interface lock" button next to the X at the top.

**Comment by SabineWren** [comment]
I should clarify, the lock button prevents moving/resizing, but it also hides UI elements when they're not in use. They're unlocked by default for initial setup.

**Comment by RonanGH** [comment]
Ah great, I hadn't tried that yet, and just assumed it only locked positions.

**Comment by SabineWren** [comment]
I had 2 people DM me on Discord with the same question. There's now a warning message in the middle of the screen.
