### ISSUE TITLE
error in battle

### ISSUE THREAD

**Issue by Qeynos** [SabineWren/Quiver#12]
the error is "Interface\AddOns\Quiver\Lib\Spellbook.lua:52: attempt to perform arithmetic on local `speedBase' (a nil value)"

Cannot determine the cause of the error, but it generally occurs during multi-enemy battles.

**Comment by SabineWren** [comment]
I haven't seen this, but I'll work on improving nil safety throughout Quiver, including the spell code.

**Comment by Qeynos** [comment]
I've disabled some code to prevent errors from showing, but this has also resulted in the loss of some features. You can refer to these locations where the errors occurred.
https://github.com/Qeynos/Quiver

**Comment by SabineWren** [comment]
Let me know if the new [beta](https://github.com/SabineWren/Quiver/tree/3.0.0-beta) fixes all above issues. Please take a look at `Locale/zhCN.translations.lua` as well, as I've marked some English with `TODO`.

**Comment by Qeynos** [comment]
I tried the beta, and the error was gone. I had never used '/qqtrueshot' before, does it disable my cast when the autoshoot is about to occur? Also, the text on the castbar remains in English.

**Comment by SabineWren** [comment]
Yes it prevents clipping, which is useful for trueshot, but not so much for multi-shot. Now it's a global function instead of a macro.

Castbar fixed 963875a8d1aa81d59501fdeea7671cd50673fb9a

**Comment by Qeynos** [comment]
Nice work! The castbar is working fine. However, when I cast Trueshot without a target, it shows the error: 'Quiver [spellcast] -- Trueshot is not on the action bars, so it can't track the cast.'

**Comment by SabineWren** [comment]
Fixed by 2da729e3a2030e16088b07cf63485239b6d761f1

**Comment by Qeynos** [comment]
This is not a text issue, is it normal behavior to get an error when casting Trueshot without a target?

**Comment by Qeynos** [comment]
And would you want to translate the warning text?

**Comment by Qeynos** [comment]
> This is not a text issue, is it normal behavior to get an error when casting Trueshot without a target?

I made a mistake, the issue fixed.

**Comment by SabineWren** [comment]
3.0.0 released. Thanks for the translations. :sparkles:

**Comment by Qeynos** [comment]
I have already using it ~
