### ISSUE TITLE
Auto shot timer bug

### ISSUE THREAD

**Issue by CrestFallen223** [SabineWren/Quiver#14]
The auto shot timer is resetting after every ability not just auto shots with the newest update.

**Comment by SabineWren** [comment]
Do you mean instants delay auto shot? That's how the game works, and Quiver now accounts for that. You can confirm this by recording video against a target dummy (even with Quiver disabled).

See the [release notes](https://github.com/SabineWren/Quiver/releases/tag/v2.7.1) and [code change.](https://github.com/SabineWren/Quiver/commit/79e74b76524ecfe54de657c5dcf165473dad55f4).

**Comment by CrestFallen223** [comment]
https://www.youtube.com/watch?v=IOgfWvnozvI
Here's a video check it out.

**Comment by SabineWren** [comment]
What am I supposed to notice?

**Comment by CrestFallen223** [comment]
I'm showing how the auto shot is coming out during the red reload animation instead of the yellow firing.

**Comment by SabineWren** [comment]
That does look wrong, but it doesn't happen for me.
