### ISSUE TITLE
Range Indicator only shows out of range and dead zone

### ISSUE THREAD

**Issue by mikemcs121** [SabineWren/Quiver#2]
The range indicator started only to show out-of-range and dead zone the "long" and "short" ranges no longer show.

**Comment by mikemcs121** [comment]
So this was pilot error, you have to have auto shot in the BottomLeft Action Buton 1

**Comment by SabineWren** [comment]
Quiver searches your action bars, so the slot doesn't matter. It should output an error message if it can't find an ability.
