### ISSUE TITLE
Undead Hunter

### ISSUE THREAD

**Issue by KopecTurtle** [SabineWren/Quiver#22]
![quiver issue](https://github.com/user-attachments/assets/931838db-a04a-4a1f-a35a-b5ab9a2e6490)
After upgrading Quiver using GitAddonsManager to the latest version the addons seems to be enabled but does not actually run. I am an undead hunter on Turtle-WoW.

**Comment by SabineWren** [comment]
https://github.com/SabineWren/Quiver?tab=readme-ov-file#option-2---clone-latest-release

**Comment by Stratodymy** [comment]
Just wanted to add my noob 2cts for the other noobs here. I use Gir addon manager and at first I tried going to the latest release page to clone the addon , but you get to pick what branch to clone from the addon manager's drop down menu under the Quiver entry.
