### ISSUE TITLE
This is more of a chair to keyboard interface issue...

### ISSUE THREAD

**Issue by Stratodymy** [SabineWren/Quiver#23]
I noticed the LUA scripts in the readme section , are these to be copied somwhere like a macro, or are they already embedded in the addon?
I tried copying the script as is and got an error, I'm obviously doing something wrong, could you perhaps explain how to use this or show me where i can find the understanding i'm lacking?

**Comment by SabineWren** [comment]
Quiver exports global functions for use in macros. The first 2 script examples in the readme are macros that I actually use, so I'm sure they work.

**Comment by Stratodymy** [comment]
I suppose I had other issues ith my game files the first time i tried it, It works perfectly now thanks for your awesome work!
