### ISSUE TITLE
customization option for autoshot

### ISSUE THREAD

**Issue by Oshire** [SabineWren/Quiver#24]
Hello! Is it possible to add 1 option to be able to set the border of the autoshot and castbar to use the tooltip border? like so

![image](https://github.com/user-attachments/assets/59a00412-a3be-4a14-b3ad-6fe152e50f30)

I tried to tweak with .lua but i always end up getting things messed up as a vertical image mess, i thought mb i need to set tile to true, but no matter it always stayed ugly as sin.

If it is not possible, no big deal. i just really love the complete look and feel of my addons to be in the same style with rounded borders =). Cheers and have a good day!

**Comment by SabineWren** [comment]
Yeah, I can add an option later.

**Comment by Oshire** [comment]
Emperor bless you!

**Comment by SabineWren** [comment]
@Oshire Released with version 3.1.0.
