### ISSUE TITLE
Can add reload remaining time or elapsed time function?

### ISSUE THREAD

**Issue by leenux** [SabineWren/Quiver#27]
Quiver.PredMidShot() is powerful feature, But some time we need get remain time of reloading, make decisions about whether we have enough free time to use trueshot or multi-shot.
The opened can same as Quiver.PredMidShot(),for example named Quiver.ReloadingRemainTime() return x.xx seconds.

Sorry for the extra workload, but I really need this feature.

GL4U.

**Comment by SabineWren** [comment]
@leenux Updated on main branch (see [changelog](https://github.com/SabineWren/Quiver/blob/main/Changelog.md)). Readme has instructions to build from source.

**Comment by leenux** [comment]
@SabineWren Thank you very much！！！ Great work！！！

**Comment by SabineWren** [comment]
@leenux Released with version 3.1.0
