### ISSUE TITLE
Aimed shot

### ISSUE THREAD

**Issue by paksedg** [SabineWren/Quiver#3]
Hello. Ive  been playing on Everlook private server realm 1.12 client.     Ive been using ur addon with no problems until about 2 weeks ago when the aimed shot bar simply dissapeared...?  Ive tried reinstaling the addon, the client, went /qq to check is all enabled and ... eveything works except the Aimed shot, i can even see the multi shot bar when casting it which is the same bar for aimed shot that just dont show when cast ....?

Help.

**Comment by SabineWren** [comment]
The most likely problem is you're using a macro to cast it, but Quiver checks your action bars to see if you're channeling whichever spell you cast. Put Aimed Shot somewhere on your action bars (hidden bars are fine) and see if that fixes it. I didn't realize this was a problem until debugging this issue, so next release I'll add a warning message to catch this.

I don't have a character on Everlook to test. Ensure you're running the latest version (2.5.3), and disable all other addons to see if any conflict (you can re-enable them later, and it won't break any configuration).

Try all 3 ways of casting the spell, as they have different code paths:
1. Clicking the spellbook entry
2. Using the ability on an action bar
3. Macro `/cast Aimed Shot`

**Comment by paksedg** [comment]
Hello.

No im not using a macro for Aimed shot. 
I am using the newest version of Quiver (but also tried older ones and they didnt work either). 
Ive already tried to disable all other addons keeping only quiver on and problem persists. Really weird all other functions of Quiver work perfectly but aimed shot cast is simply not showing. :-/

Im not home right now, but when i get there ll try ur suggestions of clicking spellbook entry or using a macro /cast Aimed shot and tell you if it worked.

Best regards.

**Comment by paksedg** [comment]
Ok, ive used the spellbook entry and it worked, i dragged the entry and replaced the old one and its working now. :)

Thx for help

**Comment by paksedg** [comment]
Hmm the bar is gone again, but if i click ont he  book entry it shows .. :-/

**Comment by paksedg** [comment]
the bar show only if i click the book ..if i drag the skill on any bar the cast wont show

**Comment by paksedg** [comment]
Ok new update .. ive made  a macro a su told me and  the macro seems to be working.  Lets give it a day or 2 to see if it will dissapear again.
