### ISSUE TITLE
Issue with setting it up

### ISSUE THREAD

**Issue by MightyTomTev** [SabineWren/Quiver#30]
Hello @SabineWren 

I'm having this issue on Turtle Wow.

I downloaded the zip, extracted and changed the name to the toc file. In game I can see the add on and I've enabled it. But I can't access the config menu and can't set it up at all. I've tried typing /qq and /Quiver but it says the command doesn't exist. 

I'm not sure what I can do to fix this, let me know if you have any suggestions. 

Thank you

**Comment by SabineWren** [comment]
Not an issue with Quiver, as the [Installation instructions](https://github.com/SabineWren/Quiver#installation) cover this. Verify the zip you downloaded includes a release version number.
