### ISSUE TITLE
Castbar

### ISSUE THREAD

**Issue by ProktorB** [SabineWren/Quiver#7]
Hey im using quiver on Turtle wow and the castbar for aimshot isnt working.
I can only get the aimshot castbar to work by clicking aimshot from my spellbook.

**Comment by SabineWren** [comment]
If you're using a macro to cast it, you need to also put the spellbook ability on your action bars.

**Comment by ProktorB** [comment]
I am not using any macros

**Comment by SabineWren** [comment]
Could try using a macro `/cast Aimed Shot` as per #3 
Another user said a game restart fixed it #5

**Comment by ProktorB** [comment]
Just tried both above.
Also tried to delete Quiver and reinstall.
Tried to disable all my addons.

Seems like i just cant get aimshot castbar to show :(

**Comment by SabineWren** [comment]
Try removing Aimed Shot from your bars, reloading your UI, and casting any spell. You should see a warning message in your chat log that Quiver can't find Aimed Shot on your action bars (it searches by icon texture). If that doesn't appear, then something's really wrong. If it does appear, then you can debug from there. Maybe try putting it elsewhere on your bars and reloading UI.

**Comment by ProktorB** [comment]
I got it to work with the use of some macro addon and having aimshot on a random keybinding.
Thanks for the help :)
